"""replace_token_columns_with_google_oauth

Revision ID: a5892720ee7c
Revises: 
Create Date: 2026-06-01 22:40:32.342242+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

#revision identifiers, used by alembic
revision: str = 'a5892720ee7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# generated by Claude after I put in the autogenerated file and it said needs to be changed

def upgrade() -> None:
    # Drop the old separate token columns
    op.drop_column("users", "calendar_token")
    op.drop_column("users", "gmail_token")

    # Add the new unified JSONB column
    op.add_column("users", sa.Column("google_oauth", postgresql.JSONB(), nullable=True))

    # Keep the index fix that autogenerate found (this part was correct)
    op.drop_constraint("users_phone_number_key", "users", type_="unique")
    op.drop_index("ix_users_phone_number", table_name="users")
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)


def downgrade() -> None:
    # Reverse — drop google_oauth, restore old columns
    op.drop_column("users", "google_oauth")
    op.add_column("users", sa.Column("calendar_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("gmail_token", sa.String(), nullable=True))

    # Reverse the index fix
    op.drop_index("ix_users_phone_number", table_name="users")
    op.create_index("ix_users_phone_number", "users", ["phone_number"], unique=False)
    op.create_unique_constraint("users_phone_number_key", "users", ["phone_number"])